version: '1'
services:
  app:
    build:
      context: ./
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      HTTP_PORT: 3000
      HTTP_HOST: 0.0.0.0
      WS_PORT: 5000
      WS_HOST: 0.0.0.0
      