version: '1'
services:
  app:
    build:
      context: ./
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      HTTP_PORT: 3000
      HTTP_HOST: 0.0.0.0
      WS_PORT: 5000
      WS_HOST: 127.0.0.1
      MONGODB_URI: mongodb://mongoserver:27017
      MONGODB_NAME: hw06
      MONGODB_COLLECTION: messages
    depends_on:
      - mongoserver
  mongoserver:
    image: mongo
    ports:
      - "27017:27017"
    volumes:
      - mongodata:/data/db
volumes:
  mongodata: